### ISSUE TITLE
Moved to JuliaLinearAlgebra

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLinearAlgebra/IterativeSolvers.jl#286]
I transferred this package to JuliaLinearAlgebra from JuliaMath. Please let me know if someone lost access - I am happy to add more folks to this org.

**Comment by mschauer** [comment]
You lost me.

**Comment by ViralBShah** [comment]
Sent invitation.

**Comment by mgr327** [comment]
Links to the 'Manual' and 'Contributing' in README.md are now broken

**Comment by ViralBShah** [comment]
fixed.
