### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by WouterJRV** [JuliaLinearAlgebra/IterativeSolvers.jl#330]
Dear all,

thank you for the great work.

I am using IterativeSolvers.jl in some recent work. In particular, I called it from the QuantumOptics.jl toolbox, the function https://docs.qojulia.org/api/#QuantumOptics.steadystate.iterative which is a wrapper around a method from here.

This works fine for a system up to a certain size (takes about 10 min to converge), but when increasing the size a little more I get the segfault core dumped and Julia exits. Any idea how this comes?

I am using Julia 1.6.3 on an Ubuntu. From watching system monitor, it doesn't look like I'm running out of RAM

EDIT: in Julia 1.8 it runs fine-at least for this system size.  Possibly trouble occurs again at larger sizes

**Comment by ViralBShah** [comment]
This would need a clear reproducer - and perhaps needs to be filed in QuantumOptics.
